MVKPipeline: Fix calculation of atomic image buffer addresses.
KhronosGroup/MoltenVK pull request #1104
Opened 2020-10-14 18:53 UTC by cdavis5e

Align the row address using the linear texture alignment for an
`R32Uint` texture.

Pull in the SPIRV-Cross changes needed to make this work.

2020-10-14 20:41 UTC, cdavis5e commented
I wonder if this should wait until KhronosGroup/SPIRV-Cross#1494 is in, so I can pull that in, too.

2020-10-15 12:38 UTC, billhollings approved these changes

2020-10-15 12:40 UTC, billhollings commented
>I wonder if this should wait until KhronosGroup/SPIRV-Cross#1494 is in, so I can pull that in, too.

Let me know. Holding off pulling this in until hearing from you.

2020-10-15 12:44 UTC, billhollings requested changes
Marking as waiting for feedback regarding bumping SPIRV-Cross version so I don't pull this in by mistake.

2020-10-16 22:07 UTC, billhollings approved these changes

2020-10-16 22:07 UTC, merged