Fix inconsistent handling of linear attachment decisions on Apple Silicon.
KhronosGroup/MoltenVK pull request #1365
Opened 2021-05-20 20:09 UTC by billhollings

Was causing some CTS attachment clearing tests to fail, or incorrectly report Not Supported, on Apple Silicon.

2021-05-20 22:51 UTC, cdavis5e requested changes
What if Intel-architecture MoltenVK finds itself running in Rosetta 2 on an Apple Silicon Mac?

2021-05-20 22:51 UTC, cdavis5e commented on MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
> +				// - On macOS IMR GPU's, Linear textures may not be used as framebuffer attachments.
```suggestion
				// - On macOS IMR GPUs, Linear textures may not be used as framebuffer attachments.
```
The apostrophe implies possession.

2021-05-21 02:11 UTC, merged

2021-05-21 12:04 UTC, billhollings commented
> What if Intel-architecture MoltenVK finds itself running in Rosetta 2 on an Apple Silicon Mac?

Dang! Sorry...because the change was just syntactic...I completely focused on this and didn't see your comment.

Good point. I hadn't considered that situation specifically. 

However...I think this makes sense. As it sits here, Intel MoltenVK under Rosetta would think it was running on an Intel Mac, just like any other Rosetta-driven Intel app, and Apple has taken on the responsibility to make Rosetta handle the silicon differences seamlessly.

I'm thinking if we wander into that territory, we might set up a situation where the app thinks it's on an Intel platform, and its characteristics because it knows no different, and we end up making changes under the covers unexpectedly.

I'm happy to hear counter-arguments.

Based on the result of that discussion, I wonder if we should adopt a consistent policy one way or another about whether an Intel MoltenVK under Rosetta should behave, and modify other internal platform tests accordingly. For instance, if my logic is correct, then perhaps all internal Apple Silicon tests should be based on compile-time arm64 testing instead of runtime Apple7 GPU testing.

2021-05-25 08:32 UTC, galad87 commented
imho capabilities should depend only on the available gpu, and not on the cpu architecture, I think there was a WWDC session that recommended to optimise for the M1 gpu even when running under rosetta.