Fix vertex buffer binding counts when establishing implicit buffers binding indexes.
KhronosGroup/MoltenVK pull request #1595
Opened 2022-05-20 13:24 UTC by billhollings

This patch fixes a regression caused by 1b6b8bc9 when the implicit buffers were moved to top of Metal buffer index range.

- Fix vertex buffer binding counts when binding indexes are not consecutive, or when additional synthetic buffer bindings are required to accommodate vertex attributes that are outside the vertex buffer stride values. 
- Include additional count for unexpected bindings.

- Set tessellation vertex buffer indexes based on platform maximum vertex stage buffer count, instead of hardcoding them, to preemptively avoid conflict with implicit buffers should the platform counts ever change.

Fixes issue #1592.

2022-05-20 13:54 UTC, FleetAdmiralButter commented
Hi @billhollings thanks for this!

This has eliminated the corruption on the title screen but it's still present once you load into the game:

[Screen Recording 2022-05-20 at 11.45.59 pm.mov](https://youtu.be/uZzj2fN3WGE)

2022-05-20 14:52 UTC, billhollings commented
> once you load into the game

Thanks for reporting. Looking at this now.

I'm not really familiar with the game. Is there a way to bypass the world login queues and long intro cutscenes to get to areas that are experiencing the problem? Otherwise, it make debugging painfully slow.

I'm testing with XIV on Mac.

2022-05-20 21:08 UTC, cdavis5e approved these changes

2022-05-22 19:58 UTC, billhollings commented
Based on [feedback](https://github.com/KhronosGroup/MoltenVK/issues/1592#issuecomment-1132946969) from the original version of this PR, I've updated this PR to properly handle the app possibly binding extra vertex attribute buffers that are not used by the current pipeline, but overlap the buffer binding range used by the implicit buffers needed by the current pipeline.

2022-05-22 20:26 UTC, ZoeyCluff commented
Nope, worse this time.
![CleanShot 2022-05-22 at 15 19 52]
![CleanShot 2022-05-22 at 15 20 13](https://user-images.githubusercontent.com/2716914/169714246-a94bcc22-97bc-4a8f-a0a5-9c3225e10ab6.png)
(https://user-images.githubusercontent.com/2716914/169714235-40697b63-5ddb-4c74-a28c-a851f9851555.png)

https://nextcloud.zoeyrae.dev/s/zGFKGkrS8ExxaCy

2022-05-22 20:59 UTC, cdavis5e approved these changes

2022-05-22 20:59 UTC, cdavis5e requested changes
Well, that didn't work...

2022-05-22 22:22 UTC, cdavis5e approved these changes
OK, glad they fixed the problems on their end.

2022-05-22 22:30 UTC, merged

2022-05-22 22:45 UTC, Gcenx commented
> OK, glad they fixed the problems on their end.

We’ve never seen the cache causing a problem between MoltenVK versions before so that was a new one.