Allow to disable Explicit LOD Workaround for Apple silicon.
KhronosGroup/MoltenVK pull request #1861
Opened 2023-04-01 21:57 UTC by italomandara

This is related to issue #1838.
Since there's a fix being worked, and it could take some time, and probably not a priority for now, it'd be nice to give at least the possibility to disable the workaround via an ENV variable like it's done with other features in the codebase.
I was thinking something like MVK_CONFIG_ENABLE_EXPLICIT_LOD_WORKAROUND= 0 to disable it and have it set to 1 by default so that it doesn't change anything compared to the current state of the codebase.
If this is a good idea I already have a branch ready, that I tested with the software affected by that issue. And I could open a PR.

2023-04-01 21:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=1861) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=1861) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/MoltenVK?pullRequest=1861) it.</sub>

2023-04-03 22:22 UTC, billhollings requested changes
Thanks for submitting this fix!

If we are to keep this fix the way it is, I've requested some changes to the documentation and layout.

But the bigger question is whether we really should add a forever config setting to the API, and when it would be employed? Looking at #1838, this appears to be an edge-case that should be resolvable via a fix to SPIRV-Cross, and we haven't finished investigating that yet.

However, I recognize that this is a regression in production, and we need to deal with it immediately. With that in mind, can we internalize the actual tracking variable? Can you rename `MVK_CONFIG_ENABLE_EXPLICIT_LOD_WORKAROUND` to `MVK_ENABLE_EXPLICIT_LOD_WORKAROUND`, and change this line in `MTLDevice.mm`:

	_metalFeatures.needsSampleDrefLodArrayWorkaround = true;

to

	MVK_SET_FROM_ENV_OR_BUILD_BOOL(_metalFeatures.needsSampleDrefLodArrayWorkaround, MVK_ENABLE_EXPLICIT_LOD_WORKAROUND);

This will internalize the variable, and use the build or env var to set it, without changes to the config API. Once the final SPIRV-Cross fix is in, we can simply ignore that env var from then on.

You can then scrap everything about `MVKConfiguration::enableExplicitLodWorkaround` (including the documentation changes I requested in this review).

And, as requested in #1838, can you submit the shader conversions that are breaking in RE3 there, please?

2023-04-04 00:10 UTC, italomandara commented
> And, as requested in #1838, can you submit the shader conversions that are breaking in RE3 there, please?
I gave the wrong shader conversion and so I deleted it will add that back soon.

2023-04-04 09:09 UTC, italomandara commented
@billhollings I squashed everything in 1 commit for convenience (to revert when the fix is ready)

2023-04-04 14:22 UTC, billhollings approved these changes
Thanks. LGTM now.

2023-04-04 14:35 UTC, merged