VisionOS build support
KhronosGroup/MoltenVK pull request #1957
Opened 2023-06-23 14:32 UTC by ifiddynine

Run-time completely untested as of now, but including the PR early.

2023-06-23 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=1957) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=1957) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/MoltenVK?pullRequest=1957) it.</sub>

2023-06-23 20:58 UTC, ifiddynine commented
Now verified that rendering works, at least in our game engine.

2023-06-28 18:57 UTC, billhollings requested changes
Nice work! Thanks for submitting it!

LGTM. And now that you've tested it out, we should be good to pull this in, once you fix the GIT conflicts.

2023-07-11 19:27 UTC, billhollings commented
Replaced by PR #1976, which fixes the conflicts, fixes build errors on older Xcode, and adds documentation. This PR was getting further and further behind the `main` branch, particularly in `MVKExtensions.def`.

2023-07-11 19:27 UTC, closed without merging