README: Add information on using Metal Frame Capture
KhronosGroup/MoltenVK pull request #1999
Opened 2023-08-19 14:12 UTC by skalarproduktraum

As the use of Metal Frame Capture is not really well documented at the moment (all the documentation I found is basically [this](https://github.com/KhronosGroup/MoltenVK/discussions/1294) discussion), I thought it'd be great to have that information available in the README as well. So this PR adds a README section on how to use Metal Frame Capture with MoltenVK 👍

2023-08-19 14:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=1999) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=1999) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/MoltenVK?pullRequest=1999) it.</sub>

2023-08-22 15:43 UTC, billhollings requested changes
Thanks for contributing this!

I made some small wording-change suggestions below.

And I think this documentation would be better located as a section in the `MoltenVK_Runtime_UserGuide.md` document, probably as a subsection of `Interacting with the **MoltenVK** Runtime`, right after `Configuring MoltenVK`.

2024-03-05 09:42 UTC, RefuX commented
@skalarproduktraum Thanks for this amazing information, I was getting really stuck trying to use the xcode graphics debugger with my LWJGL project. This is a massive help!

2024-03-08 16:57 UTC, billhollings commented
Since this PR has been sitting uncompleted for a while, I've replaced it with PR #2178, in order to move the content to the `MoltenVK_Runtime_UserGuide.md` document.

2024-03-08 16:57 UTC, closed without merging