Fix system memory size of tvOS
KhronosGroup/MoltenVK pull request #2099
Opened 2023-12-16 07:00 UTC by karelrooted

the sytem memory size of tvOS is hardcoded as 0 currently, updated to use sysctlbyname("hw.memsize") to get the correct info

apple [document](https://developer.apple.com/documentation/kernel/1387446-sysctlbyname) didn't stat this API is available on tvOS though

found this [bug](https://github.com/haasn/libplacebo/issues/229) while using libplacebo's vulkan render to play video on tvOS

2023-12-16 07:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=2099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/MoltenVK?pullRequest=2099) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/MoltenVK?pullRequest=2099) it.</sub>

2023-12-18 20:25 UTC, billhollings requested changes
Thanks for the submission!

So strange that tvOS is the only platform that doesn't support `host_info()`.

However, in testing your submission here, `sysctlbyname()` is available on all platforms, and gives the same numeric results as `host_info()` on both macOS and iOS.

So, can you modify this PR to remove the platform compile macros, and just use your new code for all platforms, please?

2023-12-19 06:32 UTC, karelrooted commented
PR is updated to use sysctlbyname to get system memory size for all apple platforms

2023-12-19 14:59 UTC, billhollings approved these changes
Thanks!

2023-12-19 14:59 UTC, merged