Add option to dump shaders
KhronosGroup/MoltenVK pull request #2210
Opened 2024-04-15 19:10 UTC by etang-cw

Adds an option to dump shaders and pipelines to a directory

When enabled, it writes the spirv and resulting msl for every shader compiled to a file named by the spirv hash

Usually a bit easier to search through than trying to look through an MVK_DEBUG=1 log, especially for pipeline link failures

2024-04-15 22:21 UTC, billhollings requested changes
Interesting idea. Thanks for submitting it.

I've requested some changes. Sorry about the confusion and lack of documentation on the `_unused_struct_padding` config element.

2024-04-16 16:53 UTC, etang-cw commented on MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
> +		snprintf(filename, sizeof(filename), "%s/pipeline%s-%016zx.txt", dumpDir, type, full_hash);
Should work fine ending in `/`, it's perfectly okay to have `//` in a path (means the same as `/`)

BTW I've updated the code to `mkdir` the directory if it doesn't already exist

2024-04-16 16:53 UTC, etang-cw commented on MoltenVK/MoltenVK/API/mvk_private_api.h
> +	const char* shaderDumpDir;                                                 /**< MVK_CONFIG_SHADER_DUMP_DIR */
Done

2024-04-16 16:57 UTC, etang-cw commented on MoltenVK/MoltenVK/API/mvk_private_api.h
>  	uint32_t _unused_struct_padding;
It is a nice reminder that the space is still there and could be used to for the next 32-bit option without breaking ABI

2024-04-16 22:21 UTC, billhollings requested changes
As mentioned in the details, once PR #2211 has been pulled in, rebase this PR on the latest `main`.

2024-04-16 22:21 UTC, billhollings commented on MoltenVK/MoltenVK/API/mvk_private_api.h
>  	uint32_t _unused_struct_padding;
Except to preserve ABI across versions (which may change the size of the `MVKConfiguration` struct), new members are only ever added to the end. See the notes above this section.

I've created PR #2211 to simplify this process, and remove this padding pseudo-member. Once that PR has been pulled in, rebase this PR on the latest `main`.

2024-04-16 22:21 UTC, billhollings commented on MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
>  MVK_CONFIG_MEMBER(_unused_struct_padding,                 uint32_t,                                 _UNUSED_STRUCT_PADDING)
As discussed above, this member is removed in PR #2211.

2024-04-16 22:21 UTC, billhollings commented on Docs/MoltenVK_Configuration_Parameters.md
> +The directory will be non-recursively created if it doesn't already exist.
As an alternate to `mkdir()`, consider using `std::filesystem:: create_directories()`, which will recursively create all the directories in the path.

2024-04-19 15:13 UTC, billhollings approved these changes
Thanks. LGTM now. 

I've made a couple of final minor syntactical edits.

2024-04-19 15:13 UTC, billhollings commented on MoltenVK/MoltenVK/Utility/MVKEnvironment.h
> + */
Align with other comments.

```suggestion
/** If set, MVK will dump spirv input, translated msl, and pipelines into the given directory. */
```

2024-04-19 15:13 UTC, billhollings commented on MoltenVK/MoltenVK/Utility/MVKEnvironment.h
>  #define MVK_CONFIG__UNUSED_STRUCT_PADDING 0
Removing as obsolete.

```suggestion
```

2024-04-19 15:14 UTC, billhollings commented on MoltenVK/MoltenVK/Utility/MVKEnvironment.h
>  #define MVK_CONFIG__UNUSED_STRUCT_PADDING 0
I've removed this now (I should have removed them on my PR).

2024-04-19 15:16 UTC, merged